<?php

namespace App\Services;

class MacVendorResolver
{
    /**
     * Diccionario compacto de OUI comunes en redes corporativas
     */
    protected static $commonVendors = [
        '00:00:0C' => 'Cisco Systems, Inc',
        '00:01:42' => 'Cisco Systems, Inc',
        '00:01:43' => 'Cisco Systems, Inc',
        '00:01:63' => 'Cisco Systems, Inc',
        '00:01:64' => 'Cisco Systems, Inc',
        '00:01:96' => 'Cisco Systems, Inc',
        '00:01:97' => 'Cisco Systems, Inc',
        '00:01:C7' => 'Cisco Systems, Inc',
        '00:01:C9' => 'Cisco Systems, Inc',
        '00:02:B9' => 'Cisco Systems, Inc',
        '00:02:FC' => 'Cisco Systems, Inc',
        '00:02:FD' => 'Cisco Systems, Inc',
        '00:03:6B' => 'Cisco Systems, Inc',
        '00:03:E3' => 'Cisco Systems, Inc',
        '00:03:E4' => 'Cisco Systems, Inc',
        '00:04:27' => 'Cisco Systems, Inc',
        '00:04:28' => 'Cisco Systems, Inc',
        '00:04:4D' => 'Cisco Systems, Inc',
        '00:04:6D' => 'Cisco Systems, Inc',
        '00:04:9A' => 'Cisco Systems, Inc',
        '00:04:C0' => 'Cisco Systems, Inc',
        '00:04:C1' => 'Cisco Systems, Inc',
        '00:05:00' => 'Cisco Systems, Inc',
        '00:05:01' => 'Cisco Systems, Inc',
        '00:05:9A' => 'Cisco Systems, Inc',
        '00:05:D7' => 'Cisco Systems, Inc',
        '00:06:52' => 'Cisco Systems, Inc',
        '00:06:53' => 'Cisco Systems, Inc',
        '00:06:D7' => 'Cisco Systems, Inc',
        '00:07:0E' => 'Cisco Systems, Inc',
        '00:07:0F' => 'Cisco Systems, Inc',
        '00:07:10' => 'Cisco Systems, Inc',
        '00:07:4F' => 'Cisco Systems, Inc',
        '00:07:50' => 'Cisco Systems, Inc',
        '00:07:85' => 'Cisco Systems, Inc',
        '00:07:86' => 'Cisco Systems, Inc',
        '00:07:B3' => 'Cisco Systems, Inc',
        '00:07:B4' => 'Cisco Systems, Inc',
        '00:08:20' => 'Cisco Systems, Inc',
        '00:08:21' => 'Cisco Systems, Inc',
        '00:08:30' => 'Cisco Systems, Inc',
        '00:08:7C' => 'Cisco Systems, Inc',
        '00:08:A3' => 'Cisco Systems, Inc',
        '00:09:7C' => 'Cisco Systems, Inc',
        '00:0A:B7' => 'Cisco Systems, Inc',
        '00:0B:85' => 'Cisco Systems, Inc',
        '00:0B:BF' => 'Cisco Systems, Inc',
        '00:0C:30' => 'Cisco Systems, Inc',
        '00:0C:85' => 'Cisco Systems, Inc',
        '00:0C:CE' => 'Cisco Systems, Inc',
        '00:0D:28' => 'Cisco Systems, Inc',
        '00:0D:29' => 'Cisco Systems, Inc',
        '00:0D:65' => 'Cisco Systems, Inc',
        '00:0D:66' => 'Cisco Systems, Inc',
        '00:0D:BC' => 'Cisco Systems, Inc',
        '00:0D:EC' => 'Cisco Systems, Inc',
        '00:0E:38' => 'Cisco Systems, Inc',
        '00:0E:D7' => 'Cisco Systems, Inc',
        '00:0F:23' => 'Cisco Systems, Inc',
        '00:0F:24' => 'Cisco Systems, Inc',
        '00:0F:8F' => 'Cisco Systems, Inc',
        '00:0F:F7' => 'Cisco Systems, Inc',
        '00:0F:F8' => 'Cisco Systems, Inc',
        '00:10:0B' => 'Cisco Systems, Inc',
        '00:10:11' => 'Cisco Systems, Inc',
        '00:10:14' => 'Cisco Systems, Inc',
        '00:10:1F' => 'Cisco Systems, Inc',
        '00:10:2F' => 'Cisco Systems, Inc',
        '00:10:7B' => 'Cisco Systems, Inc',
        '00:11:20' => 'Cisco Systems, Inc',
        '00:11:21' => 'Cisco Systems, Inc',
        '00:11:5C' => 'Cisco Systems, Inc',
        '00:11:92' => 'Cisco Systems, Inc',
        '00:11:93' => 'Cisco Systems, Inc',
        '00:11:BB' => 'Cisco Systems, Inc',
        '00:11:BC' => 'Cisco Systems, Inc',
        '00:12:00' => 'Cisco Systems, Inc',
        '00:12:01' => 'Cisco Systems, Inc',
        '00:12:43' => 'Cisco Systems, Inc',
        '00:12:44' => 'Cisco Systems, Inc',
        '00:12:7F' => 'Cisco Systems, Inc',
        '00:12:80' => 'Cisco Systems, Inc',
        '00:12:D9' => 'Cisco Systems, Inc',
        '00:13:19' => 'Cisco Systems, Inc',
        '00:13:1A' => 'Cisco Systems, Inc',
        '00:13:5F' => 'Cisco Systems, Inc',
        '00:13:60' => 'Cisco Systems, Inc',
        '00:13:C3' => 'Cisco Systems, Inc',
        '00:13:C4' => 'Cisco Systems, Inc',
        '00:14:1A' => 'Cisco Systems, Inc',
        '00:14:69' => 'Cisco Systems, Inc',
        '00:14:A4' => 'Cisco Systems, Inc',
        '00:14:F1' => 'Cisco Systems, Inc',
        '00:14:F2' => 'Cisco Systems, Inc',
        '00:15:2B' => 'Cisco Systems, Inc',
        '00:15:2C' => 'Cisco Systems, Inc',
        '00:15:62' => 'Cisco Systems, Inc',
        '00:15:63' => 'Cisco Systems, Inc',
        '00:15:C6' => 'Cisco Systems, Inc',
        '00:15:C7' => 'Cisco Systems, Inc',
        '00:15:FA' => 'Cisco Systems, Inc',
        '00:16:46' => 'Cisco Systems, Inc',
        '00:16:47' => 'Cisco Systems, Inc',
        '00:16:9D' => 'Cisco Systems, Inc',
        '00:16:C7' => 'Cisco Systems, Inc',
        '00:16:C8' => 'Cisco Systems, Inc',
        '00:17:0E' => 'Cisco Systems, Inc',
        '00:17:0F' => 'Cisco Systems, Inc',
        '00:17:3B' => 'Cisco Systems, Inc',
        '00:17:59' => 'Cisco Systems, Inc',
        '00:17:94' => 'Cisco Systems, Inc',
        '00:17:95' => 'Cisco Systems, Inc',
        '00:17:DF' => 'Cisco Systems, Inc',
        '00:17:E0' => 'Cisco Systems, Inc',
        '00:18:18' => 'Cisco Systems, Inc',
        '00:18:19' => 'Cisco Systems, Inc',
        '00:18:73' => 'Cisco Systems, Inc',
        '00:18:74' => 'Cisco Systems, Inc',
        '00:18:B9' => 'Cisco Systems, Inc',
        '00:18:BA' => 'Cisco Systems, Inc',
        '00:19:06' => 'Cisco Systems, Inc',
        '00:19:07' => 'Cisco Systems, Inc',
        '00:19:2F' => 'Cisco Systems, Inc',
        '00:19:30' => 'Cisco Systems, Inc',
        '00:19:55' => 'Cisco Systems, Inc',
        '00:19:56' => 'Cisco Systems, Inc',
        '00:19:A6' => 'Cisco Systems, Inc',
        '00:19:E7' => 'Cisco Systems, Inc',
        '00:19:E8' => 'Cisco Systems, Inc',
        '00:1A:2F' => 'Cisco Systems, Inc',
        '00:1A:30' => 'Cisco Systems, Inc',
        '00:1A:6C' => 'Cisco Systems, Inc',
        '00:1A:6D' => 'Cisco Systems, Inc',
        '00:1A:A1' => 'Cisco Systems, Inc',
        '00:1A:A2' => 'Cisco Systems, Inc',
        '00:1A:E2' => 'Cisco Systems, Inc',
        '00:1A:E3' => 'Cisco Systems, Inc',
        '00:1B:0C' => 'Cisco Systems, Inc',
        '00:1B:0D' => 'Cisco Systems, Inc',
        '00:1B:2A' => 'Cisco Systems, Inc',
        '00:1B:2B' => 'Cisco Systems, Inc',
        '00:1B:53' => 'Cisco Systems, Inc',
        '00:1B:54' => 'Cisco Systems, Inc',
        '00:1B:8F' => 'Cisco Systems, Inc',
        '00:1B:90' => 'Cisco Systems, Inc',
        '00:1B:D4' => 'Cisco Systems, Inc',
        '00:1B:D5' => 'Cisco Systems, Inc',
        '00:1C:0E' => 'Cisco Systems, Inc',
        '00:1C:0F' => 'Cisco Systems, Inc',
        '00:1C:57' => 'Cisco Systems, Inc',
        '00:1C:58' => 'Cisco Systems, Inc',
        '00:1C:B0' => 'Cisco Systems, Inc',
        '00:1C:B1' => 'Cisco Systems, Inc',
        '00:1C:DF' => 'Cisco Systems, Inc',
        '00:1C:F6' => 'Cisco Systems, Inc',
        '00:1D:45' => 'Cisco Systems, Inc',
        '00:1D:46' => 'Cisco Systems, Inc',
        '00:1D:70' => 'Cisco Systems, Inc',
        '00:1D:71' => 'Cisco Systems, Inc',
        '00:1D:A1' => 'Cisco Systems, Inc',
        '00:1D:A2' => 'Cisco Systems, Inc',
        '00:1D:E5' => 'Cisco Systems, Inc',
        '00:1D:E6' => 'Cisco Systems, Inc',
        '00:1E:13' => 'Cisco Systems, Inc',
        '00:1E:14' => 'Cisco Systems, Inc',
        '00:1E:49' => 'Cisco Systems, Inc',
        '00:1E:4A' => 'Cisco Systems, Inc',
        '00:1E:79' => 'Cisco Systems, Inc',
        '00:1E:BD' => 'Cisco Systems, Inc',
        '00:1E:BE' => 'Cisco Systems, Inc',
        '00:1E:F6' => 'Cisco Systems, Inc',
        '00:1E:F7' => 'Cisco Systems, Inc',
        '00:1F:26' => 'Cisco Systems, Inc',
        '00:1F:27' => 'Cisco Systems, Inc',
        '00:1F:6C' => 'Cisco Systems, Inc',
        '00:1F:6D' => 'Cisco Systems, Inc',
        '00:1F:9E' => 'Cisco Systems, Inc',
        '00:1F:9F' => 'Cisco Systems, Inc',
        '00:1F:CA' => 'Cisco Systems, Inc',
        '00:1F:CB' => 'Cisco Systems, Inc',
        '00:21:1B' => 'Cisco Systems, Inc',
        '00:21:1C' => 'Cisco Systems, Inc',
        '00:21:55' => 'Cisco Systems, Inc',
        '00:21:56' => 'Cisco Systems, Inc',
        '00:21:A0' => 'Cisco Systems, Inc',
        '00:21:D7' => 'Cisco Systems, Inc',
        '00:21:D8' => 'Cisco Systems, Inc',
        '00:22:55' => 'Cisco Systems, Inc',
        '00:22:90' => 'Cisco Systems, Inc',
        '00:22:BD' => 'Cisco Systems, Inc',
        '00:23:04' => 'Cisco Systems, Inc',
        '00:23:33' => 'Cisco Systems, Inc',
        '00:23:5E' => 'Cisco Systems, Inc',
        '00:23:5F' => 'Cisco Systems, Inc',
        '00:23:89' => 'Cisco Systems, Inc',
        '00:23:AC' => 'Cisco Systems, Inc',
        '00:23:EA' => 'Cisco Systems, Inc',
        '00:23:EB' => 'Cisco Systems, Inc',
        '00:24:13' => 'Cisco Systems, Inc',
        '00:24:14' => 'Cisco Systems, Inc',
        '00:24:50' => 'Cisco Systems, Inc',
        '00:24:97' => 'Cisco Systems, Inc',
        '00:24:C4' => 'Cisco Systems, Inc',
        '00:24:F4' => 'Cisco Systems, Inc',
        '00:50:56' => 'VMware, Inc.',
        '00:0C:29' => 'VMware, Inc.',
        '00:05:69' => 'VMware, Inc.',
        'E4:62:C4' => 'HP Inc.',
        'AC:4A:56' => 'HP Inc.',
        '68:7D:B4' => 'HP Inc.',
        'B4:A8:B9' => 'HP Inc.',
        '24:7E:12' => 'HP Inc.',
        '74:AD:98' => 'HP Inc.',
        '2C:0B:E9' => 'Dell Inc.',
        'F8:E5:7E' => 'Dell Inc.',
        'C8:4B:D6' => 'Dell Inc.',
        'D4:BE:D9' => 'Dell Inc.',
        '70:F0:96' => 'Cisco Systems, Inc',
        '00:16:3E' => 'Xensource, Inc.',
        '08:00:27' => 'PCS Systemtechnik GmbH (VirtualBox)',
        '52:54:00' => 'Realtek (QEMU/KVM)',
        'D4:85:64' => 'Hewlett Packard',
        '00:22:68' => 'Hewlett Packard',
        'BC:30:5B' => 'Hewlett Packard',
        '9C:8E:99' => 'Hewlett Packard',
        'C4:34:6B' => 'Hewlett Packard',
        'B4:B5:2F' => 'Hewlett Packard',
        '38:63:BB' => 'Hewlett Packard',
        '4C:42:1E' => 'Cisco Systems, Inc',
        '70:18:A7' => 'Cisco Systems, Inc',
        '02:04:35' => 'Fortinet, Inc.',
        '08:5B:0E' => 'Fortinet, Inc.',
        '00:09:0F' => 'Fortinet, Inc.',
    ];
    
    /**
     * Resolve vendor from MAC address
     */
    public static function resolveVendor($macAddress)
    {
        if (empty($macAddress)) return 'Unknown';
        
        $macUpper = strtoupper(trim($macAddress));
        
        // Ensure MAC has the correct format (e.g. 00:1A:2B:...)
        if (strpos($macUpper, ':') === false && strlen($macUpper) == 12) {
            $macUpper = wordwrap($macUpper, 2, ':', true);
        }
        
        $parts = explode(':', $macUpper);
        if (count($parts) >= 3) {
            $oui = $parts[0] . ':' . $parts[1] . ':' . $parts[2];
            
            // Local JSON cache if it exists (for a larger database)
            $jsonFile = storage_path('app/mac_vendors.json');
            if (file_exists($jsonFile)) {
                $jsonData = json_decode(file_get_contents($jsonFile), true);
                if (isset($jsonData[$oui])) {
                    return $jsonData[$oui];
                }
            }
            
            if (isset(self::$commonVendors[$oui])) {
                return self::$commonVendors[$oui];
            }
            
            // Check for virtual MACs
            if ($oui === '00:00:00') return 'Invalid / Zero';
            
            return 'Generic / Unknown';
        }
        
        return 'Unknown';
    }
}
